### ISSUE TITLE
Annotation processing not set for RELEASE_8 version

### ISSUE THREAD

**Issue by SirWindfield** [SoftSmithy/softsmithy-lib#4]
If the annotation processor gets invoked, a warning will be logged that the current annotation processor does not support java 8 source code. Changing the annotation of the annotation processor should be enough.

**Comment by puce77** [comment]
Currently the SoftSmithy Utility Library requires Java SE 7 for most modules (except softsmithy-lib-time).
But I think we could think now about migrating to Java SE 8. Then we can fix this issue as well.

**Comment by puce77** [comment]
Replaced SourceVersion.RELEASE_7 with SourceVersion.RELEASE_8
